schemaVersion: 2.2.0
metadata:
  name: lodestar
  version: 1.0.0
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      env:
        - name: QUARKUS_HTTP_HOST
          value: 0.0.0.0
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
        - exposure: public
          name: frontend
          targetPort: 3000
        - exposure: public
          name: backend
          targetPort: 8081
        - exposure: public
          name: engagements
          targetPort: 8080
      memoryLimit: 6Gi
      volumeMounts:
        - name: m2
          path: /home/user/.m2
  - name: ubi-minimal
    container:
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command: ['tail']
      args: ['-f', '/dev/null']
      memoryLimit: 64M
      mountSources: true
  - name: zookeeper
    container:
      image: docker.io/confluentinc/cp-zookeeper@latest
      env:
        - name: ZOOPKEEPER_CLIENT_PORT
          value: 2181
        - name: ZOOPKEEPER_TICK_TIME
          value: 2000
  - name: projects
    volume:
      size: 3Gi
  - name: m2
    volume:
      size: 3Gi
commands:
  - id: runtests
    exec:
      label: "Backend Test"
      component: tools
      workingDir: ${PROJECTS_ROOT}/engagements
      commandLine: "./mvnw test"
      group:
        kind: test
  - id: startdev
    exec:
      label: "Start Dev Mode"
      component: tools
      workingDir: ${PROJECTS_ROOT}/engagements
      commandLine: "./mvnw compile quarkus:dev"
      group:
        kind: run
        isDefault: true
projects:
- name: frontend
  git:
    remotes:
      origin: "https://github.com/rht-labs/lodestar-frontend.git"
- name: backend
  git:
    remotes:
      origin: "https://github.com/rht-labs/lodestar-backend.git"
- name: engagements
  git:
    remotes:
      origin: "https://github.com/rht-labs/lodestar-engagements.git"
