node {
   env.url = env.HUBOT_URL
   env.room = env.HUBOT_DEFAULT_ROOM
   
   echo env.room
   echo env.url

   hubotUrl = "HUBOT_URL=" + env.url
   hubotRoom = "HUBOT_DEFAULT_ROOM=" + env.room
   hubotFail = 'HUBOT_FAIL_ON_ERROR=false'


  withEnv([hubotUrl, hubotRoom, hubotFail]) {
    hubotSend message: 'building job hi'
    hubotApprove message: 'Proceed with building this job?'
  }

}

node('jenkins-slave-ansible') {
   
   stage('Hubot Test Pipeline') {
   echo env.room
   echo env.url
        hubotApprove message: "To proceed with this job?: your-bot-name jenkins proceed /job/${env.JOB_NAME}/${BUILD_NUMBER}/\n\nAbort job?: your-bot-name jenkins abort /job/${env.JOB_NAME}/${BUILD_NUMBER}/\n\n", failOnError: true, room: env.room, url: env.url
    }
}
